// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6Hvr6c6lLK8qcUX8XIxosOH8GdlOwrLE',
    appId: '1:154426317080:web:e0e885860c176e3dd4266d',
    messagingSenderId: '154426317080',
    projectId: 'rexcommerce-1c288',
    authDomain: 'rexcommerce-1c288.firebaseapp.com',
    storageBucket: 'rexcommerce-1c288.appspot.com',
    measurementId: 'G-FQEBGJX6KV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUJSpNIoEhcZwlp-2zvUdPo90FYLoBTho',
    appId: '1:154426317080:android:7f6150495db97246d4266d',
    messagingSenderId: '154426317080',
    projectId: 'rexcommerce-1c288',
    storageBucket: 'rexcommerce-1c288.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKHUrs82YkWawJhVlGzUBkH-yghRiP7js',
    appId: '1:154426317080:ios:6f99741573990865d4266d',
    messagingSenderId: '154426317080',
    projectId: 'rexcommerce-1c288',
    storageBucket: 'rexcommerce-1c288.appspot.com',
    iosBundleId: 'com.example.rexCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKHUrs82YkWawJhVlGzUBkH-yghRiP7js',
    appId: '1:154426317080:ios:c8dc6716d11bd1e5d4266d',
    messagingSenderId: '154426317080',
    projectId: 'rexcommerce-1c288',
    storageBucket: 'rexcommerce-1c288.appspot.com',
    iosBundleId: 'com.example.rexCommerce.RunnerTests',
  );
}
